[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "warn"
ignore = []
git-fetch-with-cli = true

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 1.0
exceptions = [
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident", version = "*" },
    { allow = ["BSD-3-Clause"], name = "matchit", version = "*" },
]

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
deny = [
    { name = "ring" },
    { name = "lazy_static" },
]
