[package]
name = "pheromone"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
prost = "0.12"
tonic = "0.10"

[build-dependencies]
tonic-build = "0.10"

[features]
bee-client = []
bee-server = []
queen-client = []
queen-server = []
hive-client = []
hive-server = []
