version: '3.4'
services:
  bee:
    ports:
      - '50051:50051'
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    build:
      context: ..
      target: hive-queen